### ISSUE TITLE
mocha-trx-reporter don't save the TRX file to disk,

### ISSUE THREAD

**Issue by saraefaf** [indigostudio/mocha-trx-reporter#29]
I am trying to use "mocha-trx-reporter" to generate the ".trx" file for my Cypress tests. I installed the "mocha-trx-reporter" version "3.3.1".I am trying to run the following command:"
npx cypress run --reporter cypress-trx-reporter --reporter-options outputDir=./custom-test-results " .
After the test is finished, the trx content is displayed in the terminal, but no trx file is created.

**Comment by pmoleri** [comment]
What's `cypress-trx-reporter`?
Does cypress automatically map it to "mocha"?
Or is it an alias maybe?

**Comment by pmoleri** [comment]
If you look at the README in this project, you'll see that the parameter is `output` not `outputDir`.

**Comment by saraefaf** [comment]
Sorry,  I wrote wrong, I tried again but still can't save. :
npx cypress run --reporter mocha-trx-reporter --reporter-options output=./custom-test-results
And here is my cypress.config.js :
 `module.exports = defineConfig({
  e2e: {
        baseUrl: 'https://localhost:5001/',
    trashAssetsBeforeRuns: true,
    viewportWidth: 1921,
    viewportHeight: 1080,   
        reporter: 'mocha-trx-reporter',
        reporterOptions: {
            reportFilename: 'cypress/custom-test-results/mytest-output.trx',
            toConsole: true, 
    },
    video: false,   
  }
});`

**Comment by pmoleri** [comment]
I haven't use this with _cypress_ but my best guess is that you copied the configuration from somewhere else and it doesn't match trx parameters.

Try:
```js
module.exports = defineConfig({
  e2e: {
    baseUrl: 'https://localhost:5001/',
    trashAssetsBeforeRuns: true,
    viewportWidth: 1921,
    viewportHeight: 1080,
    reporter: 'mocha-trx-reporter',
    reporterOptions: { output: './custom-test-results/mytest-output.trx' },
    video: false
  }
});
```

since `reportFilename` and `toConsole` are not valid mocha-trx-reporter options.

**Comment by saraefaf** [comment]
Thank you so much, it's work.
